.PHONY: all

test:
	../../build/analysis_RaytraceRefinement --n 5 --s 5

all:
	../../build/analysis_RaytraceRefinement
	# bash raytrace_all.sh
	
update:
	cp ~/PhD/projects/pov-ray/library.inc .
	cp ~/PhD/projects/pov-ray/scene.inc .
