#find_package(Boost REQUIRED COMPONENTS unit_test_framework program_options)
find_package(BLAS REQUIRED)
find_package(Eigen3 3.1.1 REQUIRED)
find_package(Delib REQUIRED)
find_package(dlib 19.4 REQUIRED)
