.PHONY: build push run

build:
	docker build -t gitlab.chab.ethz.ch:4567/sobezj/molassembler/clang6 .

push:
	docker push gitlab.chab.ethz.ch:4567/sobezj/molassembler/clang6

run:
	docker run -it gitlab.chab.ethz.ch:4567/sobezj/molassembler/clang6
